In [1]:
#implimentation of gradient decending
x1=4
x2=6
y=35
m1=4
m2=6
yp=m1*x1+m2*x2

In [2]:
yp

52

In [3]:
e=yp-y

In [4]:
e

17

In [5]:
Error=e**2

In [6]:
dem1=2*(y-yp)*(-x1)
dem2=2*(y-yp)*(-x2)
m1=m1-dem1
m2=m2-dem2

In [7]:
dem1

136

In [8]:
m2

-198

In [9]:
yp=m1*x1+m2*x2

In [10]:
yp

-1716

In [13]:
#error optimization with multiple data
import numpy as np
x1=np.random.randint(3,15,10)
x2=np.random.randint(2,20,10)
x3=np.random.randint(4,16,10)


In [15]:
x1



array([ 7,  7,  3, 14,  4, 13,  4, 12,  5,  9])

In [18]:
x=np.array([x1,x2,x3])

In [19]:
x

array([[ 7,  7,  3, 14,  4, 13,  4, 12,  5,  9],
       [16, 11, 13, 10, 14,  6, 19,  5, 13,  9],
       [13, 15, 12,  4, 14,  6,  5,  8,  4,  5]])

In [20]:
x=x.T

In [21]:
x

array([[ 7, 16, 13],
       [ 7, 11, 15],
       [ 3, 13, 12],
       [14, 10,  4],
       [ 4, 14, 14],
       [13,  6,  6],
       [ 4, 19,  5],
       [12,  5,  8],
       [ 5, 13,  4],
       [ 9,  9,  5]])

In [22]:
y=x1*4+x2*3+x3*5

In [23]:
y

array([141, 136, 111, 106, 128, 100,  98, 103,  79,  88])

In [41]:
y=y.reshape(10,1)

In [42]:
y

array([[141],
       [136],
       [111],
       [106],
       [128],
       [100],
       [ 98],
       [103],
       [ 79],
       [ 88]])

In [43]:
m=np.array([[np.random.randn(1),np.random.randn(1),np.random.randn(1)]])

In [44]:
m

array([[[-0.21227163],
        [-0.87895664],
        [-0.27096026]]])

In [45]:
#ypred=m1x1+m2x2+m3x3
# yp1-y1=e1
# yp2.y2=e2
# yp3.y3=e3
# yp4.y4=e4


yp= np.dot(x,m)



In [46]:
yp

array([[[-19.07169111]],

       [[-15.21882843]],

       [[-15.31477439]],

       [[-12.84521031]],

       [[-16.94792319]],

       [[ -9.65903264]],

       [[-18.90406402]],

       [[ -9.1097249 ]],

       [[-13.57163554]],

       [[-11.17585577]]])

In [47]:
e=yp-y

In [48]:
e

array([[[-160.07169111],
        [-155.07169111],
        [-130.07169111],
        [-125.07169111],
        [-147.07169111],
        [-119.07169111],
        [-117.07169111],
        [-122.07169111],
        [ -98.07169111],
        [-107.07169111]],

       [[-156.21882843],
        [-151.21882843],
        [-126.21882843],
        [-121.21882843],
        [-143.21882843],
        [-115.21882843],
        [-113.21882843],
        [-118.21882843],
        [ -94.21882843],
        [-103.21882843]],

       [[-156.31477439],
        [-151.31477439],
        [-126.31477439],
        [-121.31477439],
        [-143.31477439],
        [-115.31477439],
        [-113.31477439],
        [-118.31477439],
        [ -94.31477439],
        [-103.31477439]],

       [[-153.84521031],
        [-148.84521031],
        [-123.84521031],
        [-118.84521031],
        [-140.84521031],
        [-112.84521031],
        [-110.84521031],
        [-115.84521031],
        [ -91.84521031],
        [-100.84521

In [49]:
e**2

array([[[25622.94629353],
        [24047.22938247],
        [16918.64482717],
        [15642.92791611],
        [21630.08232478],
        [14178.06762284],
        [13705.78085842],
        [14901.49776948],
        [ 9618.05659639],
        [11464.3470363 ]],

       [[24404.32235679],
        [22867.13407247],
        [15931.19265085],
        [14694.00436653],
        [20511.63281755],
        [13275.37842534],
        [12818.50311161],
        [13975.69139593],
        [ 8877.18763118],
        [10654.12654296]],

       [[24434.30869366],
        [22896.16094973],
        [15955.42223006],
        [14717.27448612],
        [20539.12455944],
        [13297.4971934 ],
        [12840.23809583],
        [13998.38583976],
        [ 8895.27666888],
        [10673.94260796]],

       [[23668.34873409],
        [22154.89663103],
        [15337.63611573],
        [14124.18401267],
        [19837.37326614],
        [12734.041489  ],
        [12286.66064778],
        [13420.11275084],
      

In [50]:
dem1=2*np.dot((y-yp).T,(-x[:,:1]))
dem2=2*np.dot((y-yp).T,(-x[:,1:2]))
dem3=2*np.dot((y-yp).T,(-x[:,2:3]))

In [63]:
# dem1=dem1.reshape(1,10)
# dem2=dem2.reshape(1,10)
# dem3=dem3.reshape(1,10)


# m[0][0]=m[0][0]-dem1
# m[1][0]=m[1][0]-dem1
# m[2][0]=m[2][0]-dem1
dem1=dem1.reshape(10,1)
dem1

array([[-24021.08771168],
       [-23241.08771168],
       [-19341.08771168],
       [-18561.08771168],
       [-21993.08771168],
       [-17625.08771168],
       [-17313.08771168],
       [-18093.08771168],
       [-14349.08771168],
       [-15753.08771168]])

In [68]:
m[0][0]=m[0][0]-dem1[0][0]
m[1][0]=m[1][0]-dem2[1][0]
m[2][0]=m[2][0]-dem3[0][0]

IndexError: index 1 is out of bounds for axis 0 with size 1